name: sauder_canvas_api
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python-dotenv
  - reportlab #only used in quiz-reports
  - termcolor
  - requests
  - jupyter
  - pandas
  - datetime
  - getpass
  - pip
  - pip:
      - canvasapi
