name: sauder_canvas_api
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python-dotenv
  - reportlab
  - termcolor
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi
