name: sauder-canvas-api
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python-dotenv
  - reportlab # only used in quiz-reports
  - termcolor
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi
      - art # only used in setup-test
